

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7^yu#2_j^xp+k^7$-q1=pv4n=m0)kid+u*!_*^6^l$ycm_w=i!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'telegram_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'telegram_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'telegram_project.wsgi.app'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import json

# Add your Google Sheets credentials and other configurations
"""
Django settings for telegram_project project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7^yu#2_j^xp+k^7$-q1=pv4n=m0)kid+u*!_*^6^l$ycm_w=i!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'telegram_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'telegram_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'telegram_project.wsgi.app'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import json

# Add your Google Sheets credentials and other configurations
GOOGLE_SHEETS_CREDS_JSON = """
{
  "type": "service_account",
  "project_id": "excel-sheet-433609",
  "private_key_id": "b7a6154a8bf37ace140f8d253a49c34c6f21d1e5",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRWXM6nbgd+KUe\\nX6CuwR8A7jHLFB1pcFPc1YBXiyM2Absdn3GaeBjKVuDGY2x6LFLROLU6pNbd/CBz\\n4xApleNrTOGNeH6TDmR1cTCHhr9+A9k7+yuxmB9zw0cb0ux4KnCU0ksV0UkX0KK1\\nqVUcNAQKraNR/DY4SzCB5dEP8aQoW/viJ85ViYyf8kiMSXZC4ggIerZfYNCGs/rP\\nA7XTbmdXiOzYZk4GfjzOhbU0wBZPgrqZmozeE3yUMc7BCwTmhH32u8oQ3qoq/xMh\\n9HQftC4qhJlZdmVXm6sh9JPLfh2sfo6k+av7Tf9gDtjGpm1M3KTfMBv44yukNkq5\\nZA/4i3sRAgMBAAECggEAAibG5J7PNKGzVKou30oBsDprt26TtTWXMYfh14nk9R3x\\n8TE6FdgCFUP+HZmnp6hOd9qFHjowlFvGIYkCenxwP8Hv0xpYlKCBfqvfVMY7FpMD\\n18DdnPTxlD2sqLNcJ4wzReoAorD0yhrfFF15DSA8+2kmEibaU5t9+zzrCwzKigQK\\n1bqZXZy7xLu/np+TxROJ7Rd4viSpKXyUY9KBUfoUrg7W/l6Bw9N2EKjqYyoW5EI7\\n1BWpgkD/EIhriFU3NSDnDbkz9yXTLYC842V7xMT8hJRl8oaeljS3Y4W9pdohchWl\\nTHdOAy3Fb1KkvBwR7Bg8fRi0ErE4xx2JSKdSaNhksQKBgQDFR+4xP/5EL0BUptWO\\n9SiDjC1rulMffgmAdik3vVn4D1BbGMcpi+4T7HMVvpgnOzBi2mnevvLwUcHq3i68\\n696CZ60IZ+9TVy4LcYFpzFsajC45wvasaaf0qG46/bQBKaucOFyVgM+xxAcX6fcg\\ntESxVcOKFTnpEyqQBsvgF6p5aQKBgQC8nIeR0BdxTwWla+CRhO3gxTU1/JUC0wgP\\nq+Xpj+pYmDKpfOZsuFfCSLYBXg9J9xswDn439nxowgjHKjNVdPTiFOqkGV2Psr3y\\nyL1TwOgvjUtZQKCiss21fPF3GvMAoqSqCypG+ThRrM+YMw1IBbz8DC1jZ8XQA2Ij\\nMaHH0NVXaQKBgAUflxoEVXAj4gHQy18JEuJHs65Gin4Y4dpKN0vRSRLeIvIatKFp\\nludBjsOTzZPHP7xxe6pjPx/qn6Sf3IrffUnZs26ydE6vxuxZKEk9G2iXF2Q8ofdc\\nTxZVgXdau2AEWwaVmCHx1HMDakO+ucJJrDcGySs+3eAltUdERest8ilxAoGAOR2V\\nmDxRvQhXB18BpE+C0ZwmnvCcFzzcphJCD1Z7etSsEtM13Bp+yODH7OYU7ysbWpQo\\n+L11syt/CQDohqpiNcxrucHMqWVRTCIp4yD5rty0wpRlkJ9g1+K8JHtOtxSJlMzI\\nwrFZsrIIM2jSTsseDZ2KaR3Vs0YzA8FV4nKFCHECgYEAiw5jgtnnebytj+g8g4Bg\\nVKOfBmUniFE6wQTFp4alDIb/K/jWa7HBtkYHGyygyqDsyNi7hBw1g2uncYILdxVy\\nBwwxidcnOhxmd3AA4E1Vj4yperVI6M3KaPJVXVDv111Fhvl8oI8ow7Kpp7Jj1Tzd\\ncS56blHziW5MyniZgt5IdI8=\\n-----END PRIVATE KEY-----\\n",
  "client_email": "sushant@excel-sheet-433609.iam.gserviceaccount.com",
  "client_id": "110227970141387440393",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sushant%40excel-sheet-433609.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SPREADSHEET_NAME = 'TelegramMessages1'
API_ID = '21820068'
API_HASH = '3d2ead3813e92f494982ae522e8d49d4'
PHONE_NUMBER = '+919370529698'
SESSION_STRING = "1BVtsOIsBu1W_YwJ1nqjOh242EkRGhD-7Kr82vExpZrS0dK-HpT0S2Gz6zst1lLqWeUUeh9SWKIzDj-bnid4EO8MAtexu_S7V-NFnEsnLHFaDCgaa4eUW1MAgjTjJD1v92QsedPf-zQKN73bwVIX2VBp-vyLeXsVRroX_RqnH_woSygLLBLBhF1eHKFzaTZwx_JSRqXhDxExf4D0CHBBrwHo1zMQN5-NOUl9M2-GxU9jvkyAVh1W3p7agPu1rYq1Pdckbj7v7Slwk4hDpd-qdnzXyYjs_31Lc8G6n9vLXN8Rc0rA5E7ir9cVN0fRwW8PlRniHT1O4zm6rwG-Pr8MZNLB8dKg-D84="

CHANNEL_USERNAME_1 = 'TrendingOnDS'
CHANNEL_USERNAME_2 = 'trendingcrypto'
SPREADSHEET_NAME_1 = 'TelegramMessages1'
SPREADSHEET_NAME_2 = 'TelegramMessages2'
